# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fleek < Formula
  desc "Own your $HOME"
  homepage "https://getfleek.dev"
  version "0.9.24"
  license "Apache-2.0"

  depends_on "git"
  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ublue-os/fleek/releases/download/0.9.24/fleek_0.9.24_darwin_arm64.tar.gz"
      sha256 "591218d3478525df0b7899610183ce71db2fed676d3b76475dc75e83330fddce"

      def install
        bin.install "fleek"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ublue-os/fleek/releases/download/0.9.24/fleek_0.9.24_darwin_amd64.tar.gz"
      sha256 "8888f8a83488a2c3f5f828caba19578bb64b43d154526f48417e7ef5be7f9651"

      def install
        bin.install "fleek"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ublue-os/fleek/releases/download/0.9.24/fleek_0.9.24_linux_arm64.tar.gz"
      sha256 "0398de4e39ee55f122955f957439bb8c65b85d4aa62a5ad11a27635c3437a654"

      def install
        bin.install "fleek"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ublue-os/fleek/releases/download/0.9.24/fleek_0.9.24_linux_amd64.tar.gz"
      sha256 "f4313d793578041c4da8472c43938485257d00234732170eaa7bb7ae3ea88d94"

      def install
        bin.install "fleek"
      end
    end
  end

  test do
    system "#{bin}/fleek -v"
  end
end
