# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fleek < Formula
  desc "Own your $HOME"
  homepage "https://getfleek.dev"
  version "0.9.9"
  license "Apache-2.0"

  depends_on "go" => :optional
  depends_on "git"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ublue-os/fleek/releases/download/0.9.9/fleek_0.9.9_darwin_arm64.tar.gz"
      sha256 "7cee673ba7039b3bab7591b2adbad2c0b17ec5ec96eed09b5e9d84953dd3dec1"

      def install
        bin.install "fleek"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ublue-os/fleek/releases/download/0.9.9/fleek_0.9.9_darwin_amd64.tar.gz"
      sha256 "02758fbf21bb4360928e2f4363b0579c748d2fd9425a1e4deecf34d9b8ccca84"

      def install
        bin.install "fleek"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ublue-os/fleek/releases/download/0.9.9/fleek_0.9.9_linux_arm64.tar.gz"
      sha256 "b3f7c733aeaea1b315a5d3f85488efa73c8a8fed67aa2b55e65ee9a727148a4e"

      def install
        bin.install "fleek"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ublue-os/fleek/releases/download/0.9.9/fleek_0.9.9_linux_amd64.tar.gz"
      sha256 "d40d636601e201176e25dfe9d8cc9cfec586abb8362355e51ebd6b5086b4671a"

      def install
        bin.install "fleek"
      end
    end
  end

  test do
    system "#{bin}/fleek -v"
  end
end
